title : Creosote
tagline: Creosote Tagline
author :
  name : Sam Rawlins
  email : sam.rawlins@gmail.com
  github : srawlins
  twitter : srawlins
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
